tags:
  - name: Users
    description: API for managing users

paths:
  /api/users:
    get:
      summary: Get a list of all users
      tags: [Users]
      security:
        - BasicAuth: []
      parameters:
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [login, email, createdAt]
            default: createdAt
        - in: query
          name: sortDirection
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - in: query
          name: pageNumber
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - in: query
          name: searchLoginTerm
          schema:
            type: string
        - in: query
          name: searchEmailTerm
          schema:
            type: string
      responses:
        200:
          description: List of all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserOutputWithMeta"
    post:
      summary: Create a new user
      tags: [Users]
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        201:
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrorResponse"

  /api/users/{id}:
    delete:
      summary: Delete a user
      tags: [Users]
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: The unique identifier of the user
          schema:
            type: string
            example: "1"
      responses:
        204:
          description: User successfully deleted
        404:
          description: User not found

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    User:
      type: object
      required:
        - id
        - login
        - email
        - createdAt
      properties:
        id:
          type: string
          example: "1"
        login:
          type: string
          minLength: 3
          maxLength: 10
          example: "user1"
        email:
          type: string
          format: email
          maxLength: 100
          example: "user1@example.com"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-01T00:00:00.000Z"
    UserInput:
      type: object
      required:
        - login
        - password
        - email
      properties:
        login:
          type: string
          minLength: 3
          maxLength: 10
          pattern: "^[a-zA-Z0-9_-]*$"
          example: "user1"
        password:
          type: string
          minLength: 6
          maxLength: 20
          example: "qwerty1"
        email:
          type: string
          format: email
          maxLength: 100
          example: "user1@example.com"
    UserOutputWithMeta:
      type: object
      properties:
        pagesCount:
          type: integer
          example: 1
        page:
          type: integer
          example: 1
        pageSize:
          type: integer
          example: 10
        totalCount:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: "#/components/schemas/User"
    ValidationError:
      type: object
      properties:
        field:
          type: string
          example: "clientName"
        message:
          type: string
          example: "Client name is required"
    ValidationErrorResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
