tags:
  - name: Auth
    description: API for authentication

paths:
  /api/auth/login:
    post:
      summary: Login with loginOrEmail and password
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthInput"
      responses:
        204:
          description: Login successful
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrorResponse"
        401:
          description: Unauthorized - incorrect loginOrEmail or password

components:
  schemas:
    AuthInput:
      type: object
      required:
        - loginOrEmail
        - password
      properties:
        loginOrEmail:
          type: string
          description: User's login or email
          example: "user1"
        password:
          type: string
          minLength: 6
          maxLength: 20
          example: "qwerty1"
    ValidationError:
      type: object
      properties:
        field:
          type: string
          example: "clientName"
        message:
          type: string
          example: "Client name is required"
    ValidationErrorResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
